name: Build Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install deps
        run: |
          cd Backend
          npm install

      - name: Build
        run: |
          cd Backend
          npx tsc
