name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 136.113.204.140
          username: rain_reactor
          key: ${{ secrets.VM_SSH_KEY }}
          debug: true
          script: |
            cd ~/Brofounders/Backend
            git fetch origin
            git reset --hard origin/main
            npm install
            npx tsc
            pm2 restart backend
