name: Backend Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          cd Backend
          npm install

      - name: Build
        run: |
          cd Backend
          npx tsc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 136.113.204.140
          username: rain_reactor
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/Brofounders/Backend
            git pull origin main
            npm install
            npx tsc
            pm2 restart backend
